name: Get New Podcasts

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest
      uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Set up ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v1.1.0
      
    - name: Run Script
      run: |
        python make_rss.py
        
    - name: Commit and Push
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit --allow-empty -m "Update"
          git push
